// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: api/v1/router.proto

package apiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigService_GetRunning_FullMethodName        = "/arca.router.v1.ConfigService/GetRunning"
	ConfigService_GetCandidate_FullMethodName      = "/arca.router.v1.ConfigService/GetCandidate"
	ConfigService_EditCandidate_FullMethodName     = "/arca.router.v1.ConfigService/EditCandidate"
	ConfigService_Commit_FullMethodName            = "/arca.router.v1.ConfigService/Commit"
	ConfigService_ValidateCandidate_FullMethodName = "/arca.router.v1.ConfigService/ValidateCandidate"
	ConfigService_Discard_FullMethodName           = "/arca.router.v1.ConfigService/Discard"
	ConfigService_Rollback_FullMethodName          = "/arca.router.v1.ConfigService/Rollback"
	ConfigService_Diff_FullMethodName              = "/arca.router.v1.ConfigService/Diff"
	ConfigService_ListHistory_FullMethodName       = "/arca.router.v1.ConfigService/ListHistory"
)

// ConfigServiceClient is the client API for ConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConfigService provides configuration management operations.
// This is the internal API used by arca and the NETCONF subsystem
// to interact with the arca-routerd engine.
type ConfigServiceClient interface {
	// GetRunning returns the current running configuration.
	GetRunning(ctx context.Context, in *GetRunningRequest, opts ...grpc.CallOption) (*GetRunningResponse, error)
	// GetCandidate returns the candidate configuration for a session.
	GetCandidate(ctx context.Context, in *GetCandidateRequest, opts ...grpc.CallOption) (*GetCandidateResponse, error)
	// EditCandidate modifies the candidate configuration.
	EditCandidate(ctx context.Context, in *EditCandidateRequest, opts ...grpc.CallOption) (*EditCandidateResponse, error)
	// Commit promotes the candidate to running, applying changes.
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error)
	// ValidateCandidate validates the candidate configuration without committing it.
	ValidateCandidate(ctx context.Context, in *ValidateCandidateRequest, opts ...grpc.CallOption) (*ValidateCandidateResponse, error)
	// Discard discards candidate changes.
	Discard(ctx context.Context, in *DiscardRequest, opts ...grpc.CallOption) (*DiscardResponse, error)
	// Rollback reverts to a previous commit.
	Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error)
	// Diff returns the differences between candidate and running.
	Diff(ctx context.Context, in *DiffRequest, opts ...grpc.CallOption) (*DiffResponse, error)
	// ListHistory returns commit history.
	ListHistory(ctx context.Context, in *ListHistoryRequest, opts ...grpc.CallOption) (*ListHistoryResponse, error)
}

type configServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigServiceClient(cc grpc.ClientConnInterface) ConfigServiceClient {
	return &configServiceClient{cc}
}

func (c *configServiceClient) GetRunning(ctx context.Context, in *GetRunningRequest, opts ...grpc.CallOption) (*GetRunningResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRunningResponse)
	err := c.cc.Invoke(ctx, ConfigService_GetRunning_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) GetCandidate(ctx context.Context, in *GetCandidateRequest, opts ...grpc.CallOption) (*GetCandidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCandidateResponse)
	err := c.cc.Invoke(ctx, ConfigService_GetCandidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) EditCandidate(ctx context.Context, in *EditCandidateRequest, opts ...grpc.CallOption) (*EditCandidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditCandidateResponse)
	err := c.cc.Invoke(ctx, ConfigService_EditCandidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitResponse)
	err := c.cc.Invoke(ctx, ConfigService_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) ValidateCandidate(ctx context.Context, in *ValidateCandidateRequest, opts ...grpc.CallOption) (*ValidateCandidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateCandidateResponse)
	err := c.cc.Invoke(ctx, ConfigService_ValidateCandidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) Discard(ctx context.Context, in *DiscardRequest, opts ...grpc.CallOption) (*DiscardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscardResponse)
	err := c.cc.Invoke(ctx, ConfigService_Discard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackResponse)
	err := c.cc.Invoke(ctx, ConfigService_Rollback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) Diff(ctx context.Context, in *DiffRequest, opts ...grpc.CallOption) (*DiffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiffResponse)
	err := c.cc.Invoke(ctx, ConfigService_Diff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) ListHistory(ctx context.Context, in *ListHistoryRequest, opts ...grpc.CallOption) (*ListHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHistoryResponse)
	err := c.cc.Invoke(ctx, ConfigService_ListHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigServiceServer is the server API for ConfigService service.
// All implementations must embed UnimplementedConfigServiceServer
// for forward compatibility.
//
// ConfigService provides configuration management operations.
// This is the internal API used by arca and the NETCONF subsystem
// to interact with the arca-routerd engine.
type ConfigServiceServer interface {
	// GetRunning returns the current running configuration.
	GetRunning(context.Context, *GetRunningRequest) (*GetRunningResponse, error)
	// GetCandidate returns the candidate configuration for a session.
	GetCandidate(context.Context, *GetCandidateRequest) (*GetCandidateResponse, error)
	// EditCandidate modifies the candidate configuration.
	EditCandidate(context.Context, *EditCandidateRequest) (*EditCandidateResponse, error)
	// Commit promotes the candidate to running, applying changes.
	Commit(context.Context, *CommitRequest) (*CommitResponse, error)
	// ValidateCandidate validates the candidate configuration without committing it.
	ValidateCandidate(context.Context, *ValidateCandidateRequest) (*ValidateCandidateResponse, error)
	// Discard discards candidate changes.
	Discard(context.Context, *DiscardRequest) (*DiscardResponse, error)
	// Rollback reverts to a previous commit.
	Rollback(context.Context, *RollbackRequest) (*RollbackResponse, error)
	// Diff returns the differences between candidate and running.
	Diff(context.Context, *DiffRequest) (*DiffResponse, error)
	// ListHistory returns commit history.
	ListHistory(context.Context, *ListHistoryRequest) (*ListHistoryResponse, error)
	mustEmbedUnimplementedConfigServiceServer()
}

// UnimplementedConfigServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigServiceServer struct{}

func (UnimplementedConfigServiceServer) GetRunning(context.Context, *GetRunningRequest) (*GetRunningResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRunning not implemented")
}
func (UnimplementedConfigServiceServer) GetCandidate(context.Context, *GetCandidateRequest) (*GetCandidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCandidate not implemented")
}
func (UnimplementedConfigServiceServer) EditCandidate(context.Context, *EditCandidateRequest) (*EditCandidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditCandidate not implemented")
}
func (UnimplementedConfigServiceServer) Commit(context.Context, *CommitRequest) (*CommitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedConfigServiceServer) ValidateCandidate(context.Context, *ValidateCandidateRequest) (*ValidateCandidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateCandidate not implemented")
}
func (UnimplementedConfigServiceServer) Discard(context.Context, *DiscardRequest) (*DiscardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Discard not implemented")
}
func (UnimplementedConfigServiceServer) Rollback(context.Context, *RollbackRequest) (*RollbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rollback not implemented")
}
func (UnimplementedConfigServiceServer) Diff(context.Context, *DiffRequest) (*DiffResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Diff not implemented")
}
func (UnimplementedConfigServiceServer) ListHistory(context.Context, *ListHistoryRequest) (*ListHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHistory not implemented")
}
func (UnimplementedConfigServiceServer) mustEmbedUnimplementedConfigServiceServer() {}
func (UnimplementedConfigServiceServer) testEmbeddedByValue()                       {}

// UnsafeConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigServiceServer will
// result in compilation errors.
type UnsafeConfigServiceServer interface {
	mustEmbedUnimplementedConfigServiceServer()
}

func RegisterConfigServiceServer(s grpc.ServiceRegistrar, srv ConfigServiceServer) {
	// If the following call pancis, it indicates UnimplementedConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigService_ServiceDesc, srv)
}

func _ConfigService_GetRunning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetRunning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_GetRunning_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetRunning(ctx, req.(*GetRunningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_GetCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_GetCandidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetCandidate(ctx, req.(*GetCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_EditCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).EditCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_EditCandidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).EditCandidate(ctx, req.(*EditCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_ValidateCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).ValidateCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_ValidateCandidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).ValidateCandidate(ctx, req.(*ValidateCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_Discard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).Discard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_Discard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).Discard(ctx, req.(*DiscardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_Rollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).Rollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_Rollback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).Rollback(ctx, req.(*RollbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_Diff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).Diff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_Diff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).Diff(ctx, req.(*DiffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_ListHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).ListHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_ListHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).ListHistory(ctx, req.(*ListHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigService_ServiceDesc is the grpc.ServiceDesc for ConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arca.router.v1.ConfigService",
	HandlerType: (*ConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRunning",
			Handler:    _ConfigService_GetRunning_Handler,
		},
		{
			MethodName: "GetCandidate",
			Handler:    _ConfigService_GetCandidate_Handler,
		},
		{
			MethodName: "EditCandidate",
			Handler:    _ConfigService_EditCandidate_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _ConfigService_Commit_Handler,
		},
		{
			MethodName: "ValidateCandidate",
			Handler:    _ConfigService_ValidateCandidate_Handler,
		},
		{
			MethodName: "Discard",
			Handler:    _ConfigService_Discard_Handler,
		},
		{
			MethodName: "Rollback",
			Handler:    _ConfigService_Rollback_Handler,
		},
		{
			MethodName: "Diff",
			Handler:    _ConfigService_Diff_Handler,
		},
		{
			MethodName: "ListHistory",
			Handler:    _ConfigService_ListHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/router.proto",
}

const (
	SessionService_CreateSession_FullMethodName = "/arca.router.v1.SessionService/CreateSession"
	SessionService_CloseSession_FullMethodName  = "/arca.router.v1.SessionService/CloseSession"
	SessionService_AcquireLock_FullMethodName   = "/arca.router.v1.SessionService/AcquireLock"
	SessionService_ReleaseLock_FullMethodName   = "/arca.router.v1.SessionService/ReleaseLock"
)

// SessionServiceClient is the client API for SessionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SessionService manages configuration sessions with lock semantics.
type SessionServiceClient interface {
	// CreateSession creates a new configuration session.
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	// CloseSession closes a configuration session.
	CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error)
	// AcquireLock acquires the candidate lock for a session.
	AcquireLock(ctx context.Context, in *AcquireLockRequest, opts ...grpc.CallOption) (*AcquireLockResponse, error)
	// ReleaseLock releases the candidate lock.
	ReleaseLock(ctx context.Context, in *ReleaseLockRequest, opts ...grpc.CallOption) (*ReleaseLockResponse, error)
}

type sessionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionServiceClient(cc grpc.ClientConnInterface) SessionServiceClient {
	return &sessionServiceClient{cc}
}

func (c *sessionServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, SessionService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseSessionResponse)
	err := c.cc.Invoke(ctx, SessionService_CloseSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) AcquireLock(ctx context.Context, in *AcquireLockRequest, opts ...grpc.CallOption) (*AcquireLockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcquireLockResponse)
	err := c.cc.Invoke(ctx, SessionService_AcquireLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) ReleaseLock(ctx context.Context, in *ReleaseLockRequest, opts ...grpc.CallOption) (*ReleaseLockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseLockResponse)
	err := c.cc.Invoke(ctx, SessionService_ReleaseLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionServiceServer is the server API for SessionService service.
// All implementations must embed UnimplementedSessionServiceServer
// for forward compatibility.
//
// SessionService manages configuration sessions with lock semantics.
type SessionServiceServer interface {
	// CreateSession creates a new configuration session.
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	// CloseSession closes a configuration session.
	CloseSession(context.Context, *CloseSessionRequest) (*CloseSessionResponse, error)
	// AcquireLock acquires the candidate lock for a session.
	AcquireLock(context.Context, *AcquireLockRequest) (*AcquireLockResponse, error)
	// ReleaseLock releases the candidate lock.
	ReleaseLock(context.Context, *ReleaseLockRequest) (*ReleaseLockResponse, error)
	mustEmbedUnimplementedSessionServiceServer()
}

// UnimplementedSessionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSessionServiceServer struct{}

func (UnimplementedSessionServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedSessionServiceServer) CloseSession(context.Context, *CloseSessionRequest) (*CloseSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseSession not implemented")
}
func (UnimplementedSessionServiceServer) AcquireLock(context.Context, *AcquireLockRequest) (*AcquireLockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcquireLock not implemented")
}
func (UnimplementedSessionServiceServer) ReleaseLock(context.Context, *ReleaseLockRequest) (*ReleaseLockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseLock not implemented")
}
func (UnimplementedSessionServiceServer) mustEmbedUnimplementedSessionServiceServer() {}
func (UnimplementedSessionServiceServer) testEmbeddedByValue()                        {}

// UnsafeSessionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionServiceServer will
// result in compilation errors.
type UnsafeSessionServiceServer interface {
	mustEmbedUnimplementedSessionServiceServer()
}

func RegisterSessionServiceServer(s grpc.ServiceRegistrar, srv SessionServiceServer) {
	// If the following call pancis, it indicates UnimplementedSessionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SessionService_ServiceDesc, srv)
}

func _SessionService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_CloseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).CloseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_CloseSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).CloseSession(ctx, req.(*CloseSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_AcquireLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcquireLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).AcquireLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_AcquireLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).AcquireLock(ctx, req.(*AcquireLockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_ReleaseLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).ReleaseLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_ReleaseLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).ReleaseLock(ctx, req.(*ReleaseLockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionService_ServiceDesc is the grpc.ServiceDesc for SessionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arca.router.v1.SessionService",
	HandlerType: (*SessionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _SessionService_CreateSession_Handler,
		},
		{
			MethodName: "CloseSession",
			Handler:    _SessionService_CloseSession_Handler,
		},
		{
			MethodName: "AcquireLock",
			Handler:    _SessionService_AcquireLock_Handler,
		},
		{
			MethodName: "ReleaseLock",
			Handler:    _SessionService_ReleaseLock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/router.proto",
}

const (
	StateService_GetInterfaces_FullMethodName        = "/arca.router.v1.StateService/GetInterfaces"
	StateService_GetRoutes_FullMethodName            = "/arca.router.v1.StateService/GetRoutes"
	StateService_GetBGPNeighbors_FullMethodName      = "/arca.router.v1.StateService/GetBGPNeighbors"
	StateService_GetRouteText_FullMethodName         = "/arca.router.v1.StateService/GetRouteText"
	StateService_GetBGPSummaryText_FullMethodName    = "/arca.router.v1.StateService/GetBGPSummaryText"
	StateService_GetBGPNeighborText_FullMethodName   = "/arca.router.v1.StateService/GetBGPNeighborText"
	StateService_GetOSPFNeighborsText_FullMethodName = "/arca.router.v1.StateService/GetOSPFNeighborsText"
	StateService_GetVRRPText_FullMethodName          = "/arca.router.v1.StateService/GetVRRPText"
	StateService_GetLCPReconciliation_FullMethodName = "/arca.router.v1.StateService/GetLCPReconciliation"
	StateService_GetHAStatus_FullMethodName          = "/arca.router.v1.StateService/GetHAStatus"
	StateService_GetClassOfService_FullMethodName    = "/arca.router.v1.StateService/GetClassOfService"
	StateService_GetSystemInfo_FullMethodName        = "/arca.router.v1.StateService/GetSystemInfo"
)

// StateServiceClient is the client API for StateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StateService provides operational state queries.
type StateServiceClient interface {
	// GetInterfaces returns interface operational state.
	GetInterfaces(ctx context.Context, in *GetInterfacesRequest, opts ...grpc.CallOption) (*GetInterfacesResponse, error)
	// GetRoutes returns the routing table.
	GetRoutes(ctx context.Context, in *GetRoutesRequest, opts ...grpc.CallOption) (*GetRoutesResponse, error)
	// GetBGPNeighbors returns BGP neighbor state.
	GetBGPNeighbors(ctx context.Context, in *GetBGPNeighborsRequest, opts ...grpc.CallOption) (*GetBGPNeighborsResponse, error)
	// GetRouteText returns FRR route output for CLI display.
	GetRouteText(ctx context.Context, in *GetRouteTextRequest, opts ...grpc.CallOption) (*GetRouteTextResponse, error)
	// GetBGPSummaryText returns FRR BGP summary output for CLI display.
	GetBGPSummaryText(ctx context.Context, in *GetBGPSummaryTextRequest, opts ...grpc.CallOption) (*GetBGPSummaryTextResponse, error)
	// GetBGPNeighborText returns FRR BGP neighbor detail output for CLI display.
	GetBGPNeighborText(ctx context.Context, in *GetBGPNeighborTextRequest, opts ...grpc.CallOption) (*GetBGPNeighborTextResponse, error)
	// GetOSPFNeighborsText returns FRR OSPF neighbor output for CLI display.
	GetOSPFNeighborsText(ctx context.Context, in *GetOSPFNeighborsTextRequest, opts ...grpc.CallOption) (*GetOSPFNeighborsTextResponse, error)
	// GetVRRPText returns FRR VRRP output for CLI display.
	GetVRRPText(ctx context.Context, in *GetVRRPTextRequest, opts ...grpc.CallOption) (*GetVRRPTextResponse, error)
	// GetLCPReconciliation returns VPP LCP reconciliation state.
	GetLCPReconciliation(ctx context.Context, in *GetLCPReconciliationRequest, opts ...grpc.CallOption) (*GetLCPReconciliationResponse, error)
	// GetHAStatus returns control-plane HA convergence state.
	GetHAStatus(ctx context.Context, in *GetHAStatusRequest, opts ...grpc.CallOption) (*GetHAStatusResponse, error)
	// GetClassOfService returns running class-of-service intent.
	GetClassOfService(ctx context.Context, in *GetClassOfServiceRequest, opts ...grpc.CallOption) (*GetClassOfServiceResponse, error)
	// GetSystemInfo returns system information.
	GetSystemInfo(ctx context.Context, in *GetSystemInfoRequest, opts ...grpc.CallOption) (*GetSystemInfoResponse, error)
}

type stateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStateServiceClient(cc grpc.ClientConnInterface) StateServiceClient {
	return &stateServiceClient{cc}
}

func (c *stateServiceClient) GetInterfaces(ctx context.Context, in *GetInterfacesRequest, opts ...grpc.CallOption) (*GetInterfacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInterfacesResponse)
	err := c.cc.Invoke(ctx, StateService_GetInterfaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateServiceClient) GetRoutes(ctx context.Context, in *GetRoutesRequest, opts ...grpc.CallOption) (*GetRoutesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoutesResponse)
	err := c.cc.Invoke(ctx, StateService_GetRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateServiceClient) GetBGPNeighbors(ctx context.Context, in *GetBGPNeighborsRequest, opts ...grpc.CallOption) (*GetBGPNeighborsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBGPNeighborsResponse)
	err := c.cc.Invoke(ctx, StateService_GetBGPNeighbors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateServiceClient) GetRouteText(ctx context.Context, in *GetRouteTextRequest, opts ...grpc.CallOption) (*GetRouteTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRouteTextResponse)
	err := c.cc.Invoke(ctx, StateService_GetRouteText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateServiceClient) GetBGPSummaryText(ctx context.Context, in *GetBGPSummaryTextRequest, opts ...grpc.CallOption) (*GetBGPSummaryTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBGPSummaryTextResponse)
	err := c.cc.Invoke(ctx, StateService_GetBGPSummaryText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateServiceClient) GetBGPNeighborText(ctx context.Context, in *GetBGPNeighborTextRequest, opts ...grpc.CallOption) (*GetBGPNeighborTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBGPNeighborTextResponse)
	err := c.cc.Invoke(ctx, StateService_GetBGPNeighborText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateServiceClient) GetOSPFNeighborsText(ctx context.Context, in *GetOSPFNeighborsTextRequest, opts ...grpc.CallOption) (*GetOSPFNeighborsTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOSPFNeighborsTextResponse)
	err := c.cc.Invoke(ctx, StateService_GetOSPFNeighborsText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateServiceClient) GetVRRPText(ctx context.Context, in *GetVRRPTextRequest, opts ...grpc.CallOption) (*GetVRRPTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVRRPTextResponse)
	err := c.cc.Invoke(ctx, StateService_GetVRRPText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateServiceClient) GetLCPReconciliation(ctx context.Context, in *GetLCPReconciliationRequest, opts ...grpc.CallOption) (*GetLCPReconciliationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLCPReconciliationResponse)
	err := c.cc.Invoke(ctx, StateService_GetLCPReconciliation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateServiceClient) GetHAStatus(ctx context.Context, in *GetHAStatusRequest, opts ...grpc.CallOption) (*GetHAStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHAStatusResponse)
	err := c.cc.Invoke(ctx, StateService_GetHAStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateServiceClient) GetClassOfService(ctx context.Context, in *GetClassOfServiceRequest, opts ...grpc.CallOption) (*GetClassOfServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClassOfServiceResponse)
	err := c.cc.Invoke(ctx, StateService_GetClassOfService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateServiceClient) GetSystemInfo(ctx context.Context, in *GetSystemInfoRequest, opts ...grpc.CallOption) (*GetSystemInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSystemInfoResponse)
	err := c.cc.Invoke(ctx, StateService_GetSystemInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StateServiceServer is the server API for StateService service.
// All implementations must embed UnimplementedStateServiceServer
// for forward compatibility.
//
// StateService provides operational state queries.
type StateServiceServer interface {
	// GetInterfaces returns interface operational state.
	GetInterfaces(context.Context, *GetInterfacesRequest) (*GetInterfacesResponse, error)
	// GetRoutes returns the routing table.
	GetRoutes(context.Context, *GetRoutesRequest) (*GetRoutesResponse, error)
	// GetBGPNeighbors returns BGP neighbor state.
	GetBGPNeighbors(context.Context, *GetBGPNeighborsRequest) (*GetBGPNeighborsResponse, error)
	// GetRouteText returns FRR route output for CLI display.
	GetRouteText(context.Context, *GetRouteTextRequest) (*GetRouteTextResponse, error)
	// GetBGPSummaryText returns FRR BGP summary output for CLI display.
	GetBGPSummaryText(context.Context, *GetBGPSummaryTextRequest) (*GetBGPSummaryTextResponse, error)
	// GetBGPNeighborText returns FRR BGP neighbor detail output for CLI display.
	GetBGPNeighborText(context.Context, *GetBGPNeighborTextRequest) (*GetBGPNeighborTextResponse, error)
	// GetOSPFNeighborsText returns FRR OSPF neighbor output for CLI display.
	GetOSPFNeighborsText(context.Context, *GetOSPFNeighborsTextRequest) (*GetOSPFNeighborsTextResponse, error)
	// GetVRRPText returns FRR VRRP output for CLI display.
	GetVRRPText(context.Context, *GetVRRPTextRequest) (*GetVRRPTextResponse, error)
	// GetLCPReconciliation returns VPP LCP reconciliation state.
	GetLCPReconciliation(context.Context, *GetLCPReconciliationRequest) (*GetLCPReconciliationResponse, error)
	// GetHAStatus returns control-plane HA convergence state.
	GetHAStatus(context.Context, *GetHAStatusRequest) (*GetHAStatusResponse, error)
	// GetClassOfService returns running class-of-service intent.
	GetClassOfService(context.Context, *GetClassOfServiceRequest) (*GetClassOfServiceResponse, error)
	// GetSystemInfo returns system information.
	GetSystemInfo(context.Context, *GetSystemInfoRequest) (*GetSystemInfoResponse, error)
	mustEmbedUnimplementedStateServiceServer()
}

// UnimplementedStateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStateServiceServer struct{}

func (UnimplementedStateServiceServer) GetInterfaces(context.Context, *GetInterfacesRequest) (*GetInterfacesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInterfaces not implemented")
}
func (UnimplementedStateServiceServer) GetRoutes(context.Context, *GetRoutesRequest) (*GetRoutesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoutes not implemented")
}
func (UnimplementedStateServiceServer) GetBGPNeighbors(context.Context, *GetBGPNeighborsRequest) (*GetBGPNeighborsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBGPNeighbors not implemented")
}
func (UnimplementedStateServiceServer) GetRouteText(context.Context, *GetRouteTextRequest) (*GetRouteTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRouteText not implemented")
}
func (UnimplementedStateServiceServer) GetBGPSummaryText(context.Context, *GetBGPSummaryTextRequest) (*GetBGPSummaryTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBGPSummaryText not implemented")
}
func (UnimplementedStateServiceServer) GetBGPNeighborText(context.Context, *GetBGPNeighborTextRequest) (*GetBGPNeighborTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBGPNeighborText not implemented")
}
func (UnimplementedStateServiceServer) GetOSPFNeighborsText(context.Context, *GetOSPFNeighborsTextRequest) (*GetOSPFNeighborsTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOSPFNeighborsText not implemented")
}
func (UnimplementedStateServiceServer) GetVRRPText(context.Context, *GetVRRPTextRequest) (*GetVRRPTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVRRPText not implemented")
}
func (UnimplementedStateServiceServer) GetLCPReconciliation(context.Context, *GetLCPReconciliationRequest) (*GetLCPReconciliationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLCPReconciliation not implemented")
}
func (UnimplementedStateServiceServer) GetHAStatus(context.Context, *GetHAStatusRequest) (*GetHAStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHAStatus not implemented")
}
func (UnimplementedStateServiceServer) GetClassOfService(context.Context, *GetClassOfServiceRequest) (*GetClassOfServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClassOfService not implemented")
}
func (UnimplementedStateServiceServer) GetSystemInfo(context.Context, *GetSystemInfoRequest) (*GetSystemInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSystemInfo not implemented")
}
func (UnimplementedStateServiceServer) mustEmbedUnimplementedStateServiceServer() {}
func (UnimplementedStateServiceServer) testEmbeddedByValue()                      {}

// UnsafeStateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StateServiceServer will
// result in compilation errors.
type UnsafeStateServiceServer interface {
	mustEmbedUnimplementedStateServiceServer()
}

func RegisterStateServiceServer(s grpc.ServiceRegistrar, srv StateServiceServer) {
	// If the following call pancis, it indicates UnimplementedStateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StateService_ServiceDesc, srv)
}

func _StateService_GetInterfaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInterfacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServiceServer).GetInterfaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateService_GetInterfaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServiceServer).GetInterfaces(ctx, req.(*GetInterfacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateService_GetRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServiceServer).GetRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateService_GetRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServiceServer).GetRoutes(ctx, req.(*GetRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateService_GetBGPNeighbors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBGPNeighborsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServiceServer).GetBGPNeighbors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateService_GetBGPNeighbors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServiceServer).GetBGPNeighbors(ctx, req.(*GetBGPNeighborsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateService_GetRouteText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRouteTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServiceServer).GetRouteText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateService_GetRouteText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServiceServer).GetRouteText(ctx, req.(*GetRouteTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateService_GetBGPSummaryText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBGPSummaryTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServiceServer).GetBGPSummaryText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateService_GetBGPSummaryText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServiceServer).GetBGPSummaryText(ctx, req.(*GetBGPSummaryTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateService_GetBGPNeighborText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBGPNeighborTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServiceServer).GetBGPNeighborText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateService_GetBGPNeighborText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServiceServer).GetBGPNeighborText(ctx, req.(*GetBGPNeighborTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateService_GetOSPFNeighborsText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOSPFNeighborsTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServiceServer).GetOSPFNeighborsText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateService_GetOSPFNeighborsText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServiceServer).GetOSPFNeighborsText(ctx, req.(*GetOSPFNeighborsTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateService_GetVRRPText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVRRPTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServiceServer).GetVRRPText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateService_GetVRRPText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServiceServer).GetVRRPText(ctx, req.(*GetVRRPTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateService_GetLCPReconciliation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLCPReconciliationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServiceServer).GetLCPReconciliation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateService_GetLCPReconciliation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServiceServer).GetLCPReconciliation(ctx, req.(*GetLCPReconciliationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateService_GetHAStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHAStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServiceServer).GetHAStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateService_GetHAStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServiceServer).GetHAStatus(ctx, req.(*GetHAStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateService_GetClassOfService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClassOfServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServiceServer).GetClassOfService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateService_GetClassOfService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServiceServer).GetClassOfService(ctx, req.(*GetClassOfServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateService_GetSystemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSystemInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServiceServer).GetSystemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateService_GetSystemInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServiceServer).GetSystemInfo(ctx, req.(*GetSystemInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StateService_ServiceDesc is the grpc.ServiceDesc for StateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arca.router.v1.StateService",
	HandlerType: (*StateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInterfaces",
			Handler:    _StateService_GetInterfaces_Handler,
		},
		{
			MethodName: "GetRoutes",
			Handler:    _StateService_GetRoutes_Handler,
		},
		{
			MethodName: "GetBGPNeighbors",
			Handler:    _StateService_GetBGPNeighbors_Handler,
		},
		{
			MethodName: "GetRouteText",
			Handler:    _StateService_GetRouteText_Handler,
		},
		{
			MethodName: "GetBGPSummaryText",
			Handler:    _StateService_GetBGPSummaryText_Handler,
		},
		{
			MethodName: "GetBGPNeighborText",
			Handler:    _StateService_GetBGPNeighborText_Handler,
		},
		{
			MethodName: "GetOSPFNeighborsText",
			Handler:    _StateService_GetOSPFNeighborsText_Handler,
		},
		{
			MethodName: "GetVRRPText",
			Handler:    _StateService_GetVRRPText_Handler,
		},
		{
			MethodName: "GetLCPReconciliation",
			Handler:    _StateService_GetLCPReconciliation_Handler,
		},
		{
			MethodName: "GetHAStatus",
			Handler:    _StateService_GetHAStatus_Handler,
		},
		{
			MethodName: "GetClassOfService",
			Handler:    _StateService_GetClassOfService_Handler,
		},
		{
			MethodName: "GetSystemInfo",
			Handler:    _StateService_GetSystemInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/router.proto",
}
